This is a wonderful explanation of what I'm doing with this code.

In [ ]:
print("Hello world!")
print("I'm not ready yet")
print("Now!")

Hello world!
I'm not ready yet
Now!


Importing NumPy, commonly named "np" for short.

In [ ]:
import numpy as np

Creating an array, accessing entries by index, slicing.

In [ ]:
my_array = np.array([1,2,3,4,5])

print(my_array)
print(my_array[0])
print(my_array[1:5])
print(type(my_array))

[1 2 3 4 5]
1
[2 3 4 5]
<class 'numpy.ndarray'>


Two dimensional arrays

In [ ]:
mat = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(mat[0,1])
print(mat)
print(mat[1,-1])

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


Types for numpy arrays

'i' integer
'b' boolean
'f' float
'O' object
's' string

In [ ]:
print(my_array.dtype)

float_array = np.array([2.6, 34.5, 1.0])
print(float_array.dtype)

new_array = my_array.astype('f')
print(new_array)
print(new_array.dtype)

int64
float64
[1. 2. 3. 4. 5.]
float32


Copies and views

In [ ]:
copy_array = my_array.copy()    # deep copy, clone

copy_array[0] = 42
print(my_array)
print(copy_array)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
view_array = my_array.view()    # shallow copy, alias, view

view_array[0] = 42
print(my_array)
print(view_array)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
print(my_array.shape)

print(mat.shape)

(5,)
(2, 5)


reshaping an array

In [ ]:
one_dim_array = np.array([1,2,3,4,5,6,7,8,9,10])
two_dim_array = one_dim_array.reshape((5,2))

print(one_dim_array)
print(two_dim_array)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


When you reshape, number of entries needs to match up!

In [ ]:
other_2d_array = one_dim_array.reshape((3,3))

ValueError: ignored

Create a view, reshape the view

In [ ]:
one_dim_array = np.array([1,2,3,4,5,6,7,8,9,10])
reshaped = one_dim_array.view().reshape((5,2))

print(one_dim_array)
print(reshaped)
print(one_dim_array.shape)
print(reshaped.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(10,)
(5, 2)


Iterating through an array

In [ ]:
for x in my_array:
  print(x)

42
2
3
4
5


Concatenating arrays

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(arr1)
print(arr2)
print(combined)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr1 = arr1.reshape((2,3))
arr2 = np.array([7,8,9,10,11,12])
arr2 = arr2.reshape((2,3))

combined = np.concatenate((arr1, arr2))   # need number of columns to match
print(arr1)
print(arr2)
print(combined)

other_combined = np.concatenate((arr1, arr2), axis=1)   #need to have the same number of rows
print(other_combined)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

concatenated = np.concatenate((arr1, arr2))
stacked = np.stack((arr1, arr2))

print(concatenated)
print(stacked)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
my_array = np.array([1,6,8,4,0,5,4,0,0,2,0])

x = np.where(my_array == 0)

print(x)

(array([ 4,  7,  8, 10]),)


In [ ]:
sorted = np.sort(my_array)
print(sorted)

[0 0 0 0 1 2 4 4 5 6 8]


In [ ]:
my_array = np.array([1,6,8,4,0,5,4,0,0,2,0])

filter = [True, False, False, True, True, False, False, True, True, True, False]

filtered_array = my_array[filter]

print(filtered_array)

[1 4 0 0 0 2]


In [ ]:
""